# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 3m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-files:
    - core/genesis_alloc.go

linters:
  disable-all: true
  enable:
    - goconst
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: core/vm/instructions_test.go
      linters:
        - goconst