name: CI
on:
  push:
    branches:
      - chain4travel
  pull_request:
    branches:
      - chain4travel
  workflow_dispatch:
    inputs:
      caminogoRepo:
        description: 'caminogo github repository'
        required: true
        default: 'chain4travel/caminogo'
      caminogoBranch:
        description: 'caminogo branch'
        required: true
        default: 'chain4travel'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: check out ${{ github.event.inputs.caminogoRepo }} ${{ github.event.inputs.caminogoBranch }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.caminogoRepo }}
          ref: ${{ github.event.inputs.caminogoBranch }}
          path: caminogo
          token: ${{ secrets.CAMINO_PAT }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: change caminogo dep
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          go mod edit -replace github.com/chain4travel/caminogo=./caminogo
          go mod tidy
          go clean -modcache # avoid conflicts with the golangci-lint-action cache
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: .
          args: --timeout 3m
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.17']
        os: [macos-11.0, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.caminogoRepo }} ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.caminogoRepo }}
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
        token: ${{ secrets.CAMINO_PAT }}
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/chain4travel/caminogo=./caminogo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.17']
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.caminogoRepo }} ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.caminogoRepo }}
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
        token: ${{ secrets.CAMINO_PAT }}
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/chain4travel/caminogo=./caminogo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/test.sh -race
      shell: bash
